pageinfo = [[0,16107,0,0,null],
	[0,778,0,0,null],
	[0,773,0,0,null],
	[0,773,0,0,null],
	[0,773,0,0,null],
	[0,773,0,0,null],
	[0,29706,0,0,null],
	[0,29123,0,0,null],
	[0,29259,0,0,null],
	[0,25310,0,0,null],
	[0,25408,0,0,null],
	[0,25040,0,0,null],
	[0,25529,0,0,null],
	[0,25323,0,0,null],
	[0,34810,0,0,null],
	[0,34959,0,0,null],
	[0,13262,0,0,null],
	[0,12503,0,0,null],
	[0,15619,0,0,null],
	[0,25069,0,0,null],
	[0,25380,0,0,null],
	[0,25172,0,0,null],
	[0,25204,0,0,null],
	[0,25449,0,0,null],
	[0,25254,0,0,null],
	[0,24914,0,0,null],
	[0,25206,0,0,null],
	[0,24905,0,0,null],
	[0,25174,0,0,null],
	[0,25128,0,0,null],
	[0,35335,0,0,null],
	[0,25252,0,0,null],
	[0,34537,0,0,null],
	[0,34813,0,0,null],
	[0,13059,0,0,null],
	[0,13769,0,0,null],
	[0,12469,0,0,null],
	[0,24935,0,0,null],
	[0,32789,0,0,null],
	[0,24856,0,0,null],
	[0,35428,0,0,null],
	[0,36324,0,0,null],
	[0,34607,0,0,null],
	[0,44041,0,0,null],
	[0,13532,0,0,null],
	[0,12724,0,0,null],
	[0,12605,0,0,null],
	[0,14647,0,0,null],
	[0,24928,0,0,null],
	[0,25587,0,0,null]];
pagedata = [ ["about-us.html","How to Apply Makeup &#124; Eye Make up Tip","BeautyAddicts is a boutique cosmetics line with an effortless elegant approach to makeup that makes beauty simple with a color system designed aro...",""],
["applewebkit/index.html","Page has moved","Click here... ",""],
["applewebkit/tr/index.html","Page has moved","Click here... ",""],
["applewebkit/tr/tr/index.html","Page has moved","Click here... ",""],
["applewebkit/tr/tr/tr/index.html","Page has moved","Click here... ",""],
["applewebkit/tr/tr/tr/tr/index.html","Page has moved","Click here... ",""],
["bronzer.html","Nasıl Makyaj Yapmalı &#124; Göz Makyajı Sırları","BeautyAddicts is a boutique cosmetics line with an effortless elegant approach to makeup that makes beauty simple with a color system designed aro...",""],
["bronzera36e.html","HYDRA SUNRAYS BRONZLAŞTIRICI","Nötr mat bronzlaştırıcı pudramız sayesinde sağlıklı ışıltıyı yakalayın. Hücre yenilenmesini uyarmak için saf inci tozlarıyla formüle edilmiş, neml...",""],
["bronzerbab6.html","HYDRA SUNRAYS BRONZLAŞTIRICI &#124; bronzlaştırıcı","Nötr mat bronzlaştırıcı pudramız sayesinde sağlıklı ışıltıyı yakalayın. Hücre yenilenmesini uyarmak için saf inci tozlarıyla formüle edilmiş, neml...",""],
["brush-set.html","6 PARÇA FIRÇA SETİ","Profesyonel fırça setinin içindekiler: Açılı yüz fırçası, göz farı fırçası, geyik tabanı göz-kontur fırçası, fondöten fırçası ve çift taraflı kapa...",""],
["brush-set5200.html","6 PARÇA FIRÇA SETİ &#124; aksesuarlar","Profesyonel fırça setinin içindekiler: Açılı yüz fırçası, göz farı fırçası, geyik tabanı göz-kontur fırçası, fondöten fırçası ve çift taraflı kapa...",""],
["brush-seta36e.html","6 PARÇA FIRÇA SETİ","Professional brush set includes: angled face brush, eye shadow brush, doe foot eye-contour brush, foundation brush and double-ended concealer/angl...",""],
["brush-setbab6.html","How to Apply Makeup &#124; Eye Make up Tip","BeautyAddicts is a boutique cosmetics line with an effortless elegant approach to makeup that makes beauty simple with a color system designed aro...",""],
["brush-setd364.html","How to Apply Makeup &#124; Eye Make up Tip","BeautyAddicts is a boutique cosmetics line with an effortless elegant approach to makeup that makes beauty simple with a color system designed aro...",""],
["cheeks-blush.html","SLEEK CHEEKS ALLIK","Dinamik bir ikili: Bir tarafı kadife hafifliğinde ince parıltılı krem-pudra. Diğer tarafı mükemmel kırmızı yanaklar için ince, mat pudra. Her iki ...",""],
["cheeks-highlighters.html","GLIMMER SHEERS VURGULAYICI","Gözler, yüz ve yanaklar için en üst düzey aydınlatıcı ve vurgulayıcı ikili. Benzersiz formül birbirini tamamlayan tonlar. Glimmer: şık, pırıltılı,...",""],
["cheeks-tools.html","Yanaklar &#124; Aksesuarlar","PRO YÜZ FIRÇASI, FIRÇA SETI, KOZMETIK ÇANTASI",""],
["cheeks.html","Yanaklar","allık, bronzlaştırıcı, vurgulayıcılar, Aksesuarlar",""],
["contact-us.html","How to Apply Makeup &#124; Eye Make up Tip","BeautyAddicts is a boutique cosmetics line with an effortless elegant approach to makeup that makes beauty simple with a color system designed aro...",""],
["cosmetic-bag.html","KOZMETIK ÇANTASI","Tasarımcı imzalı bu dayanıklı naylon kumaştan çanta, ön yüzünde gümüş kaplama göz alıcı kabartmasıyla kendini güzelliğe adamış beautyADDICT&#39;ler iç...",""],
["cosmetic-bag5200.html","How to Apply Makeup &#124; Eye Make up Tip","BeautyAddicts is a boutique cosmetics line with an effortless elegant approach to makeup that makes beauty simple with a color system designed aro...",""],
["cosmetic-baga36e.html","KOZMETIK ÇANTASI","Tasarımcı imzalı bu dayanıklı naylon kumaştan çanta, ön yüzünde gümüş kaplama göz alıcı kabartmasıyla kendini güzelliğe adamış beautyADDICT&#39;ler iç...",""],
["cosmetic-bagb958.html","KOZMETIK ÇANTASI","Tasarımcı imzalı bu dayanıklı naylon kumaştan çanta, ön yüzünde gümüş kaplama göz alıcı kabartmasıyla kendini güzelliğe adamış beautyADDICT&#39;ler iç...",""],
["cosmetic-bagbab6.html","How to Apply Makeup &#124; Eye Make up Tip","BeautyAddicts is a boutique cosmetics line with an effortless elegant approach to makeup that makes beauty simple with a color system designed aro...",""],
["eye-blender-brush5200.html","How to Apply Makeup &#124; Eye Make up Tip","BeautyAddicts is a boutique cosmetics line with an effortless elegant approach to makeup that makes beauty simple with a color system designed aro...",""],
["eye-blender-brushd364.html","PRO GÖZ FARI KARIŞTIRMA FIRÇASI &#124;       fırçalar","Göz farını ve kapatıcıyı kusursuzca harmanlar ve allığı elmacık kemiklerinize mükemmelce uygular. ",""],
["eye-brow-sharper5200.html","How to Apply Makeup &#124; Eye Make up Tip","BeautyAddicts is a boutique cosmetics line with an effortless elegant approach to makeup that makes beauty simple with a color system designed aro...",""],
["eye-brow-sharperd364.html","PRO KAŞ ŞEKİLLENDİRİCİ","Açılı ucu tüyleri renklendirirken kaş fırçası şekil verir ve fazla pudrayı alır.",""],
["eye-smudge-brush5200.html","How to Apply Makeup &#124; Eye Make up Tip","BeautyAddicts is a boutique cosmetics line with an effortless elegant approach to makeup that makes beauty simple with a color system designed aro...",""],
["eye-smudge-brushd364.html","How to Apply Makeup &#124; Eye Make up Tip","BeautyAddicts is a boutique cosmetics line with an effortless elegant approach to makeup that makes beauty simple with a color system designed aro...",""],
["eyes-liners.html","EFFORTLESS EYES GÖZ KALEMİ","Her bir renk ailesi ile birlikte kullanılmak üzere yaratılmış beş özel renk:",""],
["eyes-mascara.html","SHOW OFF MASKARA","Tek bir fırça dokunuşu ile yoğun, çarpıcı kirpikler! Bu eşsiz formül Argan yağı ile kirpikleri yumuşatır ve korurken hacimli, uzun ve kıvrık kirpi...",""],
["eyes-shadow-play.html","PLAY GÖZ FARI","Süper ince, öğütülmüş sedeflerle göz alıcı bakışlar yaratır ve kremsi bir uygulama sunar. Uzun süre dayanıklı, pırıltılı renkler ortaya koyar.",""],
["eyes-shadow-solutions.html","SOLUTION EYES GÖZ FARI","Eşsiz dörtlü göz farı paletimiz pırıltılıdan mata, ışıltılıya farklı sonuçlar alabileceğiniz birbiriyle uyumlu dört renk tonu içerir. Tamamı kusur...",""],
["eyes-shadows.html","GÖZLER &#124; Farlar","SOLUTION EYES GÖZ FARI, PLAY GÖZ FARI ",""],
["eyes-tools.html","gözler &#124; aksesuarlar","PRO GÖZ FARI KARIŞTIRMA FIRÇASI, PRO SMUDGE DAĞITMA FIRÇASI, PRO KAŞ ŞEKİLLENDİRİCİ, KOZMETIK ÇANTASI, FIRÇA SETI",""],
["eyes.html","GÖZLER","Maskara, Göz Farları, Göz Kalemleri, Göz Kalemleri, Aksesuarlar",""],
["face-brusha36e.html","PRO YÜZ FIRÇASI","Çok fonksiyonlu bu yüz fırçası fondöteninizi bronzlaştırıcınızı veya vurgulayıcınızı kolaylıkla uygulamanızı sağlar.",""],
["face-brushbab6.html","PRO YÜZ FIRÇASI &#124; Yüz","Çok fonksiyonlu bu yüz firçasi fondöteninizi bronzlaştırıcınizi veya vurgulayicinizi  kolaylikla uygulamanizi saglar.",""],
["face-brushd364.html","PRO YÜZ FIRÇASI &#124; fırçalar","Çok fonksiyonlu bu yüz firçasi fondöteninizi bronzlaştırıcınizi veya vurgulayicinizi  kolaylikla uygulamanizi saglar.",""],
["face-concealers.html","DOUBLE DECEPTION KAPATICI","Bu ikili kapatıcı iki farklı formül içerir: Yatıştırıcı göz altı formülü (sağ bölüm) Yeşil Çay ve E Vitamini ile hassas cildi yatıştırır. Yüz form...",""],
["face-foundations.html","FACE2FACE FONDÖTEN","Anında kusursuz kapatıcılık sağlar. Bu tam kapatıcı fondöten, pürüzsüzlük ve koruma için A, E vitaminleri ve Yeşil Çay ile zenginleştirilmiştir. D...",""],
["face-powders.html","FLAWLESS COVER SIKIŞTIRILMIŞ PUDRA &#124; pudralar","Bu pudra hafiften ortaya kadar pürüzsüz ve kadife dokuda bir kapama sağlar. Papatya ile doldurulmuştur, cildi yatıştırır, korur ve onarırken ince ...",""],
["face-tinted-moisturizers.html","MINERAL SHEER TINT  RENKLİ NEMLENDİRİCİ","İdeal, neredeyse görünmeyen, yedi doğal renk tonuna sahip ",""],
["face-tools.html","How to Apply Makeup &#124; Eye Make up Tip","BeautyAddicts is a boutique cosmetics line with an effortless elegant approach to makeup that makes beauty simple with a color system designed aro...",""],
["face.html","Yüz","RENKLİ NEMLENDİRİCİler, fondötenler, kapatıcılar, pudralar, bronzlaştırıcı, Aksesuarlar",""],
["find-us.html","How to Apply Makeup &#124; Eye Make up Tip","BeautyAddicts is a boutique cosmetics line with an effortless elegant approach to makeup that makes beauty simple with a color system designed aro...",""],
["index.html","Beauty ADDICTS &#124; Beauty Made Simple","BeautyAddicts is a boutique cosmetics line with an effortless elegant approach to makeup that makes beauty simple with a color system designed aro...",""],
["lip-clickb958.html","LIP CLICK AKILLI DUDAK FIRÇASI","Açılıp kapanabilen ruj fırçası tek bir hareketle tamamen açılır ve kullandıktan sonra geri kayarak tam korumalı kutusuna geri girer. Hem parlatıcı...",""],
["lip-clickd364.html","LIP CLICK AKILLI DUDAK FIRÇASI &#124;       fırçalar","Açılıp kapanabilen ruj fırçası tek bir hareketle tamamen açılır ve kullandıktan sonra geri kayarak tam korumalı kutusuna geri girer. Hem parlatıcı...",""]];
